/********************************************************************************\

                   Plugin-based Microbiome Analysis (PluMA)

        Copyright (C) 2016, 2018-2020, 2026 Bioinformatics Research Group (BioRG)
                       Florida International University


     Permission is hereby granted, free of charge, to any person obtaining
          a copy of this software and associated documentation files
        (the "Software"), to deal in the Software without restriction,
      including without limitation the rights to use, copy, modify, merge,
      publish, distribute, sublicense, and/or sell copies of the Software,
       and to permit persons to whom the Software is furnished to do so,
                    subject to the following conditions:

    The above copyright notice and this permission notice shall be included
            in all copies or substantial portions of the Software.

        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
     IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
     CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
      TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
           SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

       For information regarding this software, please contact lead architect
                    Trevor Cickovski at tcickovs@fiu.edu

\*********************************************************************************/

#include "JuliaPluginGenerator.h"
#include <dirent.h>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <algorithm>

JuliaPluginGenerator::JuliaPluginGenerator(std::string path, bool literal) {
    myPath = path;
    myLiteral = literal;
}

void JuliaPluginGenerator::generate(std::string pluginname, std::vector<std::string>& command) {
    makeDirectory(pluginname);
    makeJuliaFile(pluginname, command);
    makeReadme(pluginname, command);
}

void JuliaPluginGenerator::makeDirectory(std::string pluginname) {
    std::string directory = myPath + "/" + pluginname;
    DIR* dir = opendir(directory.c_str());
    if (!dir) {
        system(("mkdir -p " + directory).c_str());
    }
}

void JuliaPluginGenerator::makeJuliaFile(std::string pluginname, std::vector<std::string>& command) {
    std::string juliafile = myPath + "/" + pluginname + "/" + pluginname + "Plugin.jl";
    std::ofstream jlfile(juliafile.c_str(), std::ios::out);

    // Module documentation
    jlfile << "#=" << std::endl;
    jlfile << "PluMA Plugin: " << pluginname << std::endl;
    jlfile << "Generated by PluGen" << std::endl;
    jlfile << "=# " << std::endl;
    jlfile << std::endl;

    // Global variables for plugin state
    jlfile << "# Plugin state" << std::endl;
    jlfile << "input_file = \"\"" << std::endl;
    jlfile << "output_file = \"\"" << std::endl;
    if (!myLiteral) {
        jlfile << "parameters = Dict{String, String}()" << std::endl;
    }
    jlfile << std::endl;

    // Helper function to read parameters
    if (!myLiteral) {
        jlfile << "\"\"\"" << std::endl;
        jlfile << "    read_parameters(filepath::String)" << std::endl;
        jlfile << std::endl;
        jlfile << "Read tab-delimited parameter file into dictionary." << std::endl;
        jlfile << "\"\"\"" << std::endl;
        jlfile << "function read_parameters(filepath::String)" << std::endl;
        jlfile << "    params = Dict{String, String}()" << std::endl;
        jlfile << "    open(filepath, \"r\") do file" << std::endl;
        jlfile << "        for line in eachline(file)" << std::endl;
        jlfile << "            parts = split(line, '\\t')" << std::endl;
        jlfile << "            if length(parts) >= 2" << std::endl;
        jlfile << "                params[strip(parts[1])] = strip(parts[2])" << std::endl;
        jlfile << "            end" << std::endl;
        jlfile << "        end" << std::endl;
        jlfile << "    end" << std::endl;
        jlfile << "    return params" << std::endl;
        jlfile << "end" << std::endl;
        jlfile << std::endl;
    }

    // Input function
    jlfile << "\"\"\"" << std::endl;
    jlfile << "    input(filepath::String)" << std::endl;
    jlfile << std::endl;
    jlfile << "Read input parameters from file." << std::endl;
    jlfile << "Called by PluMA before run()." << std::endl;
    jlfile << "\"\"\"" << std::endl;
    jlfile << "function input(filepath::String)" << std::endl;
    jlfile << "    global input_file = filepath" << std::endl;
    if (!myLiteral) {
        jlfile << "    global parameters = read_parameters(filepath)" << std::endl;
    }
    jlfile << "end" << std::endl;
    jlfile << std::endl;

    // Run function
    jlfile << "\"\"\"" << std::endl;
    jlfile << "    run()" << std::endl;
    jlfile << std::endl;
    jlfile << "Execute the main plugin logic." << std::endl;
    jlfile << "Called by PluMA after input() and before output()." << std::endl;
    jlfile << "\"\"\"" << std::endl;
    jlfile << "function run()" << std::endl;
    jlfile << "    # Main computation goes here" << std::endl;
    jlfile << "    # Access parameters via: parameters[\"key\"]" << std::endl;
    jlfile << "end" << std::endl;
    jlfile << std::endl;

    // Output function
    jlfile << "\"\"\"" << std::endl;
    jlfile << "    output(filepath::String)" << std::endl;
    jlfile << std::endl;
    jlfile << "Write results to output file." << std::endl;
    jlfile << "Called by PluMA after run()." << std::endl;
    jlfile << "\"\"\"" << std::endl;
    jlfile << "function output(filepath::String)" << std::endl;
    jlfile << "    global output_file = filepath" << std::endl;

    // Build command if provided
    if (!command.empty()) {
        jlfile << std::endl;
        jlfile << "    # Build and execute command" << std::endl;
        jlfile << "    cmd_parts = String[]" << std::endl;
        jlfile << "    push!(cmd_parts, \"" << command[0] << "\")" << std::endl;

        bool optionalflag = false;
        for (size_t i = 1; i < command.size(); i++) {
            if (myLiteral && command[i] == "inputfile") {
                jlfile << "    push!(cmd_parts, input_file)" << std::endl;
            } else if (command[i] == "outputfile") {
                jlfile << "    push!(cmd_parts, output_file)" << std::endl;
            } else if (command[i][0] == '[') {
                optionalflag = true;
            } else if (command[i][0] == ']') {
                optionalflag = false;
            } else if (command[i][0] == '-') {
                if (i + 1 < command.size() && command[i+1] != "inputfile" && command[i+1] != "outputfile") {
                    if (optionalflag) {
                        jlfile << "    if haskey(parameters, \"" << command[i+1] << "\")" << std::endl;
                        jlfile << "        push!(cmd_parts, \"" << command[i] << "\")" << std::endl;
                        jlfile << "        push!(cmd_parts, parameters[\"" << command[i+1] << "\"])" << std::endl;
                        jlfile << "    end" << std::endl;
                    } else {
                        jlfile << "    push!(cmd_parts, \"" << command[i] << "\")" << std::endl;
                        jlfile << "    push!(cmd_parts, parameters[\"" << command[i+1] << "\"])" << std::endl;
                    }
                    i++;
                } else {
                    jlfile << "    push!(cmd_parts, \"" << command[i] << "\")" << std::endl;
                }
            } else if (!optionalflag) {
                jlfile << "    push!(cmd_parts, parameters[\"" << command[i] << "\"])" << std::endl;
            } else {
                jlfile << "    if haskey(parameters, \"" << command[i] << "\")" << std::endl;
                jlfile << "        push!(cmd_parts, parameters[\"" << command[i] << "\"])" << std::endl;
                jlfile << "    end" << std::endl;
            }
        }

        jlfile << std::endl;
        jlfile << "    # Execute the command" << std::endl;
        jlfile << "    cmd = Cmd(cmd_parts)" << std::endl;
        jlfile << "    try" << std::endl;
        jlfile << "        run(cmd)" << std::endl;
        jlfile << "    catch e" << std::endl;
        jlfile << "        @error \"Command execution failed\" exception=e" << std::endl;
        jlfile << "    end" << std::endl;
    }

    jlfile << "end" << std::endl;
    jlfile << std::endl;

    // Helper functions
    if (!myLiteral) {
        jlfile << "\"\"\"" << std::endl;
        jlfile << "    get_parameter(key::String, default::String=\"\")" << std::endl;
        jlfile << std::endl;
        jlfile << "Get a parameter value with optional default." << std::endl;
        jlfile << "\"\"\"" << std::endl;
        jlfile << "function get_parameter(key::String, default::String=\"\")" << std::endl;
        jlfile << "    return get(parameters, key, default)" << std::endl;
        jlfile << "end" << std::endl;
        jlfile << std::endl;

        jlfile << "\"\"\"" << std::endl;
        jlfile << "    has_parameter(key::String)" << std::endl;
        jlfile << std::endl;
        jlfile << "Check if a parameter exists." << std::endl;
        jlfile << "\"\"\"" << std::endl;
        jlfile << "function has_parameter(key::String)" << std::endl;
        jlfile << "    return haskey(parameters, key)" << std::endl;
        jlfile << "end" << std::endl;
    }

    jlfile.close();
    std::cout << "Generated: " << juliafile << std::endl;
}

void JuliaPluginGenerator::makeReadme(std::string pluginname, std::vector<std::string>& command) {
    std::string readme = myPath + "/" + pluginname + "/README.md";
    std::ofstream readmefile(readme.c_str(), std::ios::out);

    std::cout << "ENTER OUTPUT FORMAT: ";
    std::string outputfmt;
    std::cin >> outputfmt;

    std::cout << "ENTER DEPENDENCIES: ";
    std::string dependencies;
    std::cin >> dependencies;

    readmefile << "# " << pluginname << std::endl;
    readmefile << std::endl;
    readmefile << "## Overview" << std::endl;
    readmefile << std::endl;
    readmefile << "- **Language:** Julia" << std::endl;
    readmefile << "- **Input:** TXT (tab-delimited parameter file)" << std::endl;
    readmefile << "- **Output:** " << outputfmt << std::endl;
    readmefile << "- **Tested with:** PluMA 2.0+, Julia 1.6+" << std::endl;
    if (!dependencies.empty() && dependencies != "none") {
        readmefile << "- **Dependencies:** " << dependencies << std::endl;
    }
    readmefile << std::endl;

    readmefile << "## Description" << std::endl;
    readmefile << std::endl;
    readmefile << "PluMA plugin that runs " << pluginname << "." << std::endl;
    readmefile << std::endl;

    readmefile << "## Parameters" << std::endl;
    readmefile << std::endl;
    readmefile << "The plugin expects a parameter file with tab-delimited keyword-value pairs:" << std::endl;
    readmefile << std::endl;

    bool optionalflag = false;
    for (size_t i = 1; i < command.size(); i++) {
        if (command[i][0] == '[') {
            optionalflag = true;
        } else if (command[i][0] == ']') {
            optionalflag = false;
        } else if (command[i][0] == '-') {
            if (i + 1 < command.size() && command[i+1] != "inputfile" && command[i+1] != "outputfile") {
                if (optionalflag) {
                    readmefile << "- `" << command[i+1] << "` (optional, flag: " << command[i] << ")" << std::endl;
                } else {
                    readmefile << "- `" << command[i+1] << "` (required, flag: " << command[i] << ")" << std::endl;
                }
                i++;
            }
        } else if (command[i] != "inputfile" && command[i] != "outputfile") {
            if (optionalflag) {
                readmefile << "- `" << command[i] << "` (optional)" << std::endl;
            } else {
                readmefile << "- `" << command[i] << "` (required)" << std::endl;
            }
        }
    }

    readmefile << std::endl;
    readmefile << "## Usage" << std::endl;
    readmefile << std::endl;
    readmefile << "In your PluMA pipeline file:" << std::endl;
    readmefile << std::endl;
    readmefile << "```" << std::endl;
    readmefile << "Plugin " << pluginname << " inputfile params.txt outputfile output." << outputfmt << std::endl;
    readmefile << "```" << std::endl;
    readmefile << std::endl;

    readmefile << "## Julia Plugin Structure" << std::endl;
    readmefile << std::endl;
    readmefile << "Julia plugins must define three functions:" << std::endl;
    readmefile << std::endl;
    readmefile << "```julia" << std::endl;
    readmefile << "function input(filepath::String)" << std::endl;
    readmefile << "    # Read parameters from filepath" << std::endl;
    readmefile << "end" << std::endl;
    readmefile << std::endl;
    readmefile << "function run()" << std::endl;
    readmefile << "    # Main computation" << std::endl;
    readmefile << "end" << std::endl;
    readmefile << std::endl;
    readmefile << "function output(filepath::String)" << std::endl;
    readmefile << "    # Write results to filepath" << std::endl;
    readmefile << "end" << std::endl;
    readmefile << "```" << std::endl;

    readmefile.close();
    std::cout << "Generated: " << readme << std::endl;
}
