/********************************************************************************\

                   Plugin-based Microbiome Analysis (PluMA)

        Copyright (C) 2016, 2018-2020, 2026 Bioinformatics Research Group (BioRG)
                       Florida International University

\*********************************************************************************/

#include "PythonPluginGenerator.h"
#include <dirent.h>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <algorithm>

PythonPluginGenerator::PythonPluginGenerator(std::string path, bool literal) {
    myPath = path;
    myLiteral = literal;
}

void PythonPluginGenerator::generate(std::string pluginname, std::vector<std::string>& command) {
    makeDirectory(pluginname);
    makePythonFile(pluginname, command);
    makeRequirements(pluginname);
    makeReadme(pluginname, command);
}

void PythonPluginGenerator::makeDirectory(std::string pluginname) {
    std::string directory = myPath + "/" + pluginname;
    DIR* dir = opendir(directory.c_str());
    if (!dir) {
        system(("mkdir -p " + directory).c_str());
    }
}

void PythonPluginGenerator::makePythonFile(std::string pluginname, std::vector<std::string>& command) {
    // Emit a Python plugin matching the existing PluMA convention seen
    // across plugins/*/* on master:
    //   * Class name = <PluginName>Plugin, in file <PluginName>Plugin.py
    //   * input(self, inputfile) reads parameters via PyIO.readParameters
    //     (tab-delimited key/value, exposed by PluMA's PyIO.py)
    //   * run(self) typically empty for wrapper plugins
    //   * output(self, outputfile) does the real work; uses
    //     PyPluMA.prefix() + "/" + self.parameters["key"] to resolve
    //     paths relative to the pipeline prefix
    //   * No __init__, no type hints, no auto-subprocess scaffold —
    //     existing plugins write their own I/O directly. The generator
    //     leaves run() empty and adds a TODO in output() so the user
    //     can fill in plugin logic.
    std::string pyfile = myPath + "/" + pluginname + "/" + pluginname + "Plugin.py";
    std::ofstream py(pyfile.c_str(), std::ios::out);

    // Module docstring + imports. Always pull in PyPluMA + PyIO so the
    // generated plugin has the conventional access path to the pipeline
    // prefix and parameter parser even when the scaffold doesn't use
    // them directly yet.
    py << "# PluMA Plugin: " << pluginname << " (generated by PluGen)" << std::endl;
    py << "#" << std::endl;
    py << "# PluMA's embedded Python loader looks for a class named" << std::endl;
    py << "# " << pluginname << "Plugin in this file and calls input/run/output on" << std::endl;
    py << "# a fresh instance as the pipeline executes." << std::endl;
    py << std::endl;
    py << "import PyIO       # PluMA-provided: PyIO.readParameters(path) -> dict" << std::endl;
    py << "import PyPluMA    # PluMA-provided: PyPluMA.prefix() returns the pipeline prefix" << std::endl;
    if (!command.empty()) {
        py << "import os         # for os.system() in output()" << std::endl;
    }
    py << std::endl;
    py << std::endl;

    // Class definition — no docstring, no __init__, matching the
    // existing plugin style. State is set as side-effects in
    // input()/run()/output().
    py << "class " << pluginname << "Plugin:" << std::endl;

    // input() — read parameters via PyIO; no type hints.
    py << "    def input(self, inputfile):" << std::endl;
    if (myLiteral) {
        // Literal-inputfile mode: caller passes the data file directly,
        // there's no parameter file to parse. Just stash the path.
        py << "        self.inputfile = inputfile" << std::endl;
    } else {
        py << "        self.parameters = PyIO.readParameters(inputfile)" << std::endl;
    }
    py << std::endl;

    // run() — kept empty per convention. Heavy lifting goes in output().
    py << "    def run(self):" << std::endl;
    py << "        pass" << std::endl;
    py << std::endl;

    // output() — either the canonical "wrap an external command" pattern
    // (using PyPluMA.prefix() to resolve relative paths from the
    // parameter file) or an empty scaffold with a TODO.
    py << "    def output(self, outputfile):" << std::endl;
    if (command.empty()) {
        if (myLiteral) {
            py << "        # TODO: read self.inputfile, do work, write to outputfile." << std::endl;
            py << "        pass" << std::endl;
        } else {
            py << "        # TODO: use self.parameters[...] (paths resolved with" << std::endl;
            py << "        # PyPluMA.prefix() + \"/\" + ...) and write to outputfile." << std::endl;
            py << "        pass" << std::endl;
        }
    } else {
        // Build a shell command string in the style used by existing
        // PluMA Python wrapper plugins (e.g. AntibodyBLAST). Path tokens
        // from the parameter file are prefixed with PyPluMA.prefix().
        py << "        cmd = \"" << command[0] << "\"" << std::endl;

        bool optionalflag = false;
        for (size_t i = 1; i < command.size(); i++) {
            if (myLiteral && command[i] == "inputfile") {
                py << "        cmd += \" \" + self.inputfile" << std::endl;
            } else if (command[i] == "outputfile") {
                py << "        cmd += \" \" + outputfile" << std::endl;
            } else if (command[i][0] == '[') {
                optionalflag = true;
            } else if (command[i][0] == ']') {
                optionalflag = false;
            } else if (command[i][0] == '-') {
                if (i + 1 < command.size() && command[i + 1] != "inputfile" && command[i + 1] != "outputfile") {
                    if (optionalflag) {
                        py << "        if \"" << command[i + 1] << "\" in self.parameters:" << std::endl;
                        py << "            cmd += \" " << command[i] << " \" + PyPluMA.prefix() + \"/\" + self.parameters[\"" << command[i + 1] << "\"]" << std::endl;
                    } else {
                        py << "        cmd += \" " << command[i] << " \" + PyPluMA.prefix() + \"/\" + self.parameters[\"" << command[i + 1] << "\"]" << std::endl;
                    }
                    i++;
                } else {
                    py << "        cmd += \" " << command[i] << "\"" << std::endl;
                }
            } else if (!optionalflag) {
                py << "        cmd += \" \" + self.parameters[\"" << command[i] << "\"]" << std::endl;
            } else {
                py << "        if \"" << command[i] << "\" in self.parameters:" << std::endl;
                py << "            cmd += \" \" + self.parameters[\"" << command[i] << "\"]" << std::endl;
            }
        }

        py << "        os.system(cmd)" << std::endl;
    }

    py.close();
    std::cout << "Generated: " << pyfile << std::endl;
}

void PythonPluginGenerator::makeRequirements(std::string pluginname) {
    // PluMA's shared-plugin-venv flow (resolve_requirements.py) reads each
    // plugin's requirements.txt at scons time and installs into a project-
    // root .venv. An empty stub here keeps that flow happy without pinning
    // anything by default.
    std::string reqfile = myPath + "/" + pluginname + "/requirements.txt";
    std::ofstream req(reqfile.c_str(), std::ios::out);
    req << "# PluMA plugin dependencies (one per line, pip-format). Leave empty if" << std::endl;
    req << "# the plugin uses only the standard library. Listed packages are merged" << std::endl;
    req << "# across all plugins by resolve_requirements.py and installed into the" << std::endl;
    req << "# project-root .venv at scons time." << std::endl;
    req.close();
    std::cout << "Generated: " << reqfile << std::endl;
}

void PythonPluginGenerator::makeReadme(std::string pluginname, std::vector<std::string>& command) {
    std::string readme = myPath + "/" + pluginname + "/README.md";
    std::ofstream readmefile(readme.c_str(), std::ios::out);

    std::cout << "ENTER OUTPUT FORMAT: ";
    std::string outputfmt;
    std::cin >> outputfmt;

    std::cout << "ENTER DEPENDENCIES: ";
    std::string dependencies;
    std::cin >> dependencies;

    readmefile << "# " << pluginname << std::endl;
    readmefile << std::endl;
    readmefile << "## Overview" << std::endl;
    readmefile << std::endl;
    readmefile << "- **Language:** Python" << std::endl;
    readmefile << "- **Input:** TXT (tab-delimited parameter file)" << std::endl;
    readmefile << "- **Output:** " << outputfmt << std::endl;
    readmefile << "- **Tested with:** PluMA 2.0+, Python 3.10+" << std::endl;
    if (!dependencies.empty() && dependencies != "none") {
        readmefile << "- **Dependencies:** " << dependencies << std::endl;
    }
    readmefile << std::endl;

    readmefile << "## Description" << std::endl;
    readmefile << std::endl;
    readmefile << "PluMA plugin that runs " << pluginname << "." << std::endl;
    readmefile << std::endl;

    readmefile << "## Parameters" << std::endl;
    readmefile << std::endl;
    readmefile << "The plugin expects a parameter file with whitespace-delimited key/value pairs (`#` introduces a comment):" << std::endl;
    readmefile << std::endl;

    bool optionalflag = false;
    for (size_t i = 1; i < command.size(); i++) {
        if (command[i][0] == '[') {
            optionalflag = true;
        } else if (command[i][0] == ']') {
            optionalflag = false;
        } else if (command[i][0] == '-') {
            if (i + 1 < command.size() && command[i + 1] != "inputfile" && command[i + 1] != "outputfile") {
                if (optionalflag) {
                    readmefile << "- `" << command[i + 1] << "` (optional, flag: " << command[i] << ")" << std::endl;
                } else {
                    readmefile << "- `" << command[i + 1] << "` (required, flag: " << command[i] << ")" << std::endl;
                }
                i++;
            }
        } else if (command[i] != "inputfile" && command[i] != "outputfile") {
            if (optionalflag) {
                readmefile << "- `" << command[i] << "` (optional)" << std::endl;
            } else {
                readmefile << "- `" << command[i] << "` (required)" << std::endl;
            }
        }
    }

    readmefile << std::endl;
    readmefile << "## Usage" << std::endl;
    readmefile << std::endl;
    readmefile << "In your PluMA pipeline file:" << std::endl;
    readmefile << std::endl;
    readmefile << "```" << std::endl;
    readmefile << "Plugin " << pluginname << " inputfile params.txt outputfile output." << outputfmt << std::endl;
    readmefile << "```" << std::endl;
    readmefile << std::endl;

    readmefile << "## Python Plugin Structure" << std::endl;
    readmefile << std::endl;
    readmefile << "Python plugins must define a class `<Name>Plugin` with three methods:" << std::endl;
    readmefile << std::endl;
    readmefile << "```python" << std::endl;
    readmefile << "class " << pluginname << "Plugin:" << std::endl;
    readmefile << "    def input(self, filename: str) -> None: ..." << std::endl;
    readmefile << "    def run(self) -> None: ..." << std::endl;
    readmefile << "    def output(self, filename: str) -> None: ..." << std::endl;
    readmefile << "```" << std::endl;
    readmefile << std::endl;
    readmefile << "PluMA instantiates the class and calls the three methods in order." << std::endl;

    readmefile.close();
    std::cout << "Generated: " << readme << std::endl;
}
