/********************************************************************************\

                   Plugin-based Microbiome Analysis (PluMA)

        Copyright (C) 2016, 2018-2020, 2026 Bioinformatics Research Group (BioRG)
                       Florida International University

\*********************************************************************************/

#include "PythonPluginGenerator.h"
#include <dirent.h>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <algorithm>

PythonPluginGenerator::PythonPluginGenerator(std::string path, bool literal) {
    myPath = path;
    myLiteral = literal;
}

void PythonPluginGenerator::generate(std::string pluginname, std::vector<std::string>& command) {
    makeDirectory(pluginname);
    makePythonFile(pluginname, command);
    makeRequirements(pluginname);
    makeReadme(pluginname, command);
}

void PythonPluginGenerator::makeDirectory(std::string pluginname) {
    std::string directory = myPath + "/" + pluginname;
    DIR* dir = opendir(directory.c_str());
    if (!dir) {
        system(("mkdir -p " + directory).c_str());
    }
}

void PythonPluginGenerator::makePythonFile(std::string pluginname, std::vector<std::string>& command) {
    std::string pyfile = myPath + "/" + pluginname + "/" + pluginname + "Plugin.py";
    std::ofstream py(pyfile.c_str(), std::ios::out);

    // File docstring.
    py << "\"\"\"" << std::endl;
    py << "PluMA Plugin: " << pluginname << std::endl;
    py << std::endl;
    py << "Generated by PluGen. PluMA's Python loader looks for a class named" << std::endl;
    py << "`<Name>Plugin` in `<Name>Plugin.py` under the plugin directory, and" << std::endl;
    py << "calls input(filename) / run() / output(filename) on a fresh instance" << std::endl;
    py << "as the pipeline executes." << std::endl;
    py << "\"\"\"" << std::endl;
    py << std::endl;

    if (!command.empty()) {
        py << "import subprocess" << std::endl;
    }
    py << std::endl;
    py << std::endl;

    // Class definition.
    py << "class " << pluginname << "Plugin:" << std::endl;
    py << "    \"\"\"Single-class PluMA plugin entry point.\"\"\"" << std::endl;
    py << std::endl;

    // __init__: state for parameters / filenames.
    py << "    def __init__(self):" << std::endl;
    py << "        self.input_file = \"\"" << std::endl;
    py << "        self.output_file = \"\"" << std::endl;
    if (!myLiteral) {
        py << "        self.parameters: dict[str, str] = {}" << std::endl;
    }
    py << std::endl;

    // Helper: parse tab-delimited parameter file.
    if (!myLiteral) {
        py << "    def _read_parameters(self, filepath: str) -> dict[str, str]:" << std::endl;
        py << "        \"\"\"Parse a PluMA-convention parameter file.\"\"\"" << std::endl;
        py << "        params: dict[str, str] = {}" << std::endl;
        py << "        with open(filepath, \"r\") as fh:" << std::endl;
        py << "            for raw in fh:" << std::endl;
        py << "                line = raw.split(\"#\", 1)[0].strip()" << std::endl;
        py << "                if not line:" << std::endl;
        py << "                    continue" << std::endl;
        py << "                parts = line.split(None, 1) if \"\\t\" not in line else line.split(\"\\t\", 1)" << std::endl;
        py << "                if len(parts) == 2:" << std::endl;
        py << "                    params[parts[0].strip()] = parts[1].strip()" << std::endl;
        py << "        return params" << std::endl;
        py << std::endl;
    }

    // input()
    py << "    def input(self, filename: str) -> None:" << std::endl;
    py << "        \"\"\"Called by PluMA with the pre-prefixed input path.\"\"\"" << std::endl;
    py << "        self.input_file = filename" << std::endl;
    if (!myLiteral) {
        py << "        self.parameters = self._read_parameters(filename)" << std::endl;
    }
    py << std::endl;

    // run()
    py << "    def run(self) -> None:" << std::endl;
    py << "        \"\"\"Main computation. Called after input() and before output().\"\"\"" << std::endl;
    if (command.empty()) {
        py << "        # TODO: implement plugin logic here." << std::endl;
        py << "        pass" << std::endl;
    } else {
        py << "        # Default scaffold defers heavy work to output(), where the" << std::endl;
        py << "        # output path is known. Override in your plugin if you'd" << std::endl;
        py << "        # prefer to compute here and just write in output()." << std::endl;
        py << "        pass" << std::endl;
    }
    py << std::endl;

    // output()
    py << "    def output(self, filename: str) -> None:" << std::endl;
    py << "        \"\"\"Called by PluMA with the pre-prefixed output path.\"\"\"" << std::endl;
    py << "        self.output_file = filename" << std::endl;

    if (!command.empty()) {
        py << std::endl;
        py << "        # Build and execute the wrapped command." << std::endl;
        py << "        cmd: list[str] = [\"" << command[0] << "\"]" << std::endl;

        bool optionalflag = false;
        for (size_t i = 1; i < command.size(); i++) {
            if (myLiteral && command[i] == "inputfile") {
                py << "        cmd.append(self.input_file)" << std::endl;
            } else if (command[i] == "outputfile") {
                py << "        cmd.append(self.output_file)" << std::endl;
            } else if (command[i][0] == '[') {
                optionalflag = true;
            } else if (command[i][0] == ']') {
                optionalflag = false;
            } else if (command[i][0] == '-') {
                if (i + 1 < command.size() && command[i + 1] != "inputfile" && command[i + 1] != "outputfile") {
                    if (optionalflag) {
                        py << "        if \"" << command[i + 1] << "\" in self.parameters:" << std::endl;
                        py << "            cmd.append(\"" << command[i] << "\")" << std::endl;
                        py << "            cmd.append(self.parameters[\"" << command[i + 1] << "\"])" << std::endl;
                    } else {
                        py << "        cmd.append(\"" << command[i] << "\")" << std::endl;
                        py << "        cmd.append(self.parameters[\"" << command[i + 1] << "\"])" << std::endl;
                    }
                    i++;
                } else {
                    py << "        cmd.append(\"" << command[i] << "\")" << std::endl;
                }
            } else if (!optionalflag) {
                py << "        cmd.append(self.parameters[\"" << command[i] << "\"])" << std::endl;
            } else {
                py << "        if \"" << command[i] << "\" in self.parameters:" << std::endl;
                py << "            cmd.append(self.parameters[\"" << command[i] << "\"])" << std::endl;
            }
        }

        py << std::endl;
        py << "        print(\"[" << pluginname << "] running:\", \" \".join(cmd))" << std::endl;
        py << "        subprocess.run(cmd, check=False)" << std::endl;
    } else {
        py << std::endl;
        py << "        # TODO: write results to self.output_file." << std::endl;
    }
    py << std::endl;

    // Helper accessors (only meaningful when parameters dict exists).
    if (!myLiteral) {
        py << "    def get_parameter(self, key: str, default: str = \"\") -> str:" << std::endl;
        py << "        \"\"\"Look up a parameter with optional default.\"\"\"" << std::endl;
        py << "        return self.parameters.get(key, default)" << std::endl;
        py << std::endl;

        py << "    def has_parameter(self, key: str) -> bool:" << std::endl;
        py << "        \"\"\"Check if a parameter was supplied.\"\"\"" << std::endl;
        py << "        return key in self.parameters" << std::endl;
    }

    py.close();
    std::cout << "Generated: " << pyfile << std::endl;
}

void PythonPluginGenerator::makeRequirements(std::string pluginname) {
    // PluMA's shared-plugin-venv flow (resolve_requirements.py) reads each
    // plugin's requirements.txt at scons time and installs into a project-
    // root .venv. An empty stub here keeps that flow happy without pinning
    // anything by default.
    std::string reqfile = myPath + "/" + pluginname + "/requirements.txt";
    std::ofstream req(reqfile.c_str(), std::ios::out);
    req << "# PluMA plugin dependencies (one per line, pip-format). Leave empty if" << std::endl;
    req << "# the plugin uses only the standard library. Listed packages are merged" << std::endl;
    req << "# across all plugins by resolve_requirements.py and installed into the" << std::endl;
    req << "# project-root .venv at scons time." << std::endl;
    req.close();
    std::cout << "Generated: " << reqfile << std::endl;
}

void PythonPluginGenerator::makeReadme(std::string pluginname, std::vector<std::string>& command) {
    std::string readme = myPath + "/" + pluginname + "/README.md";
    std::ofstream readmefile(readme.c_str(), std::ios::out);

    std::cout << "ENTER OUTPUT FORMAT: ";
    std::string outputfmt;
    std::cin >> outputfmt;

    std::cout << "ENTER DEPENDENCIES: ";
    std::string dependencies;
    std::cin >> dependencies;

    readmefile << "# " << pluginname << std::endl;
    readmefile << std::endl;
    readmefile << "## Overview" << std::endl;
    readmefile << std::endl;
    readmefile << "- **Language:** Python" << std::endl;
    readmefile << "- **Input:** TXT (tab-delimited parameter file)" << std::endl;
    readmefile << "- **Output:** " << outputfmt << std::endl;
    readmefile << "- **Tested with:** PluMA 2.0+, Python 3.10+" << std::endl;
    if (!dependencies.empty() && dependencies != "none") {
        readmefile << "- **Dependencies:** " << dependencies << std::endl;
    }
    readmefile << std::endl;

    readmefile << "## Description" << std::endl;
    readmefile << std::endl;
    readmefile << "PluMA plugin that runs " << pluginname << "." << std::endl;
    readmefile << std::endl;

    readmefile << "## Parameters" << std::endl;
    readmefile << std::endl;
    readmefile << "The plugin expects a parameter file with whitespace-delimited key/value pairs (`#` introduces a comment):" << std::endl;
    readmefile << std::endl;

    bool optionalflag = false;
    for (size_t i = 1; i < command.size(); i++) {
        if (command[i][0] == '[') {
            optionalflag = true;
        } else if (command[i][0] == ']') {
            optionalflag = false;
        } else if (command[i][0] == '-') {
            if (i + 1 < command.size() && command[i + 1] != "inputfile" && command[i + 1] != "outputfile") {
                if (optionalflag) {
                    readmefile << "- `" << command[i + 1] << "` (optional, flag: " << command[i] << ")" << std::endl;
                } else {
                    readmefile << "- `" << command[i + 1] << "` (required, flag: " << command[i] << ")" << std::endl;
                }
                i++;
            }
        } else if (command[i] != "inputfile" && command[i] != "outputfile") {
            if (optionalflag) {
                readmefile << "- `" << command[i] << "` (optional)" << std::endl;
            } else {
                readmefile << "- `" << command[i] << "` (required)" << std::endl;
            }
        }
    }

    readmefile << std::endl;
    readmefile << "## Usage" << std::endl;
    readmefile << std::endl;
    readmefile << "In your PluMA pipeline file:" << std::endl;
    readmefile << std::endl;
    readmefile << "```" << std::endl;
    readmefile << "Plugin " << pluginname << " inputfile params.txt outputfile output." << outputfmt << std::endl;
    readmefile << "```" << std::endl;
    readmefile << std::endl;

    readmefile << "## Python Plugin Structure" << std::endl;
    readmefile << std::endl;
    readmefile << "Python plugins must define a class `<Name>Plugin` with three methods:" << std::endl;
    readmefile << std::endl;
    readmefile << "```python" << std::endl;
    readmefile << "class " << pluginname << "Plugin:" << std::endl;
    readmefile << "    def input(self, filename: str) -> None: ..." << std::endl;
    readmefile << "    def run(self) -> None: ..." << std::endl;
    readmefile << "    def output(self, filename: str) -> None: ..." << std::endl;
    readmefile << "```" << std::endl;
    readmefile << std::endl;
    readmefile << "PluMA instantiates the class and calls the three methods in order." << std::endl;

    readmefile.close();
    std::cout << "Generated: " << readme << std::endl;
}
