/********************************************************************************\

                   Plugin-based Microbiome Analysis (PluMA)

        Copyright (C) 2016, 2018-2020, 2026 Bioinformatics Research Group (BioRG)
                       Florida International University

\*********************************************************************************/

#include "RPluginGenerator.h"
#include <dirent.h>
#include <cstdlib>
#include <fstream>
#include <iostream>

RPluginGenerator::RPluginGenerator(std::string path, bool literal) {
    myPath = path;
    myLiteral = literal;
}

void RPluginGenerator::generate(std::string pluginname, std::vector<std::string>& command) {
    makeDirectory(pluginname);
    makeRFile(pluginname, command);
    makeReadme(pluginname, command);
}

void RPluginGenerator::makeDirectory(std::string pluginname) {
    std::string directory = myPath + "/" + pluginname;
    DIR* dir = opendir(directory.c_str());
    if (!dir) {
        system(("mkdir -p " + directory).c_str());
    }
}

void RPluginGenerator::makeRFile(std::string pluginname, std::vector<std::string>& command) {
    // Emit an R plugin matching the existing PluMA convention seen
    // across plugins/*/*.R on master:
    //
    //   * Three top-level functions, not an S4/R6 class:
    //         input  <- function(inputfile) { ... }
    //         run    <- function() { ... }
    //         output <- function(outputfile) { ... }
    //   * RPluMA boilerplate that loads the dyn-lib + RPluMA.R helper,
    //     making prefix() available for joining paths from the parameter
    //     file against the pipeline prefix.
    //   * Parameter-file mode (no literal "inputfile" in the command):
    //         parameters <<- read.table(inputfile, as.is=T)
    //         rownames(parameters) <<- parameters[,1]
    //         somepath   <<- paste(pfix, parameters["key", 2], sep="/")
    //   * Literal-inputfile mode:
    //         data <<- read.csv(inputfile)
    //         (or just the path stored, depending on what run() needs)
    //   * Global state via the <<- super-assignment operator so values
    //     set in input() are visible to run() and output().
    //
    // No type annotations (R doesn't have them); no docstring class
    // (existing R plugins are bare functions); the run() body is left
    // empty to match the common "do all the work in output()" pattern.

    std::string rfile = myPath + "/" + pluginname + "/" + pluginname + "Plugin.R";
    std::ofstream r(rfile.c_str(), std::ios::out);

    // Header comment block.
    r << "# PluMA Plugin: " << pluginname << " (generated by PluGen)" << std::endl;
    r << "#" << std::endl;
    r << "# PluMA's embedded R loader invokes input(inputfile) / run() /" << std::endl;
    r << "# output(outputfile) defined as top-level functions in this file." << std::endl;
    r << "# State persists between calls via the <<- super-assignment operator." << std::endl;
    r << std::endl;

    // RPluMA boilerplate (provides the prefix() helper). Always emitted
    // — even literal-inputfile plugins may want it for output paths.
    r << "dyn.load(paste(\"RPluMA\", .Platform$dynlib.ext, sep=\"\"))" << std::endl;
    r << "source(\"RPluMA.R\")" << std::endl;
    r << std::endl;

    // Library hints. Leave commented out so the user can uncomment
    // anything they actually need — matches the "library(...)" lines at
    // the top of nearly every plugin under plugins/*/*.R.
    r << "# library(<package>)   # uncomment any dependencies you need" << std::endl;
    r << std::endl;

    // input() — read parameters or directly read the data, depending on
    // command shape.
    r << "input <- function(inputfile) {" << std::endl;
    if (myLiteral) {
        // Literal-inputfile mode: store the path (and optionally
        // read.csv it eagerly, matching ABLine/Gauss).
        r << "  inputfile <<- inputfile" << std::endl;
    } else {
        // Parameter-file mode: PluMA convention — read tab-delimited
        // key/value pairs, key the rows by the first column, expose
        // the prefix for path joining.
        r << "  pfix <<- prefix()" << std::endl;
        r << "  parameters <<- read.table(inputfile, as.is=T)" << std::endl;
        r << "  rownames(parameters) <<- parameters[,1]" << std::endl;

        // For each path-like parameter token (i.e. anything that looks
        // like a file or directory key in the command spec), emit a
        // path-join line. Heuristic: tokens that immediately follow a
        // "-flag" or that appear bare get the prefix join; this mirrors
        // how existing plugins like Shannon/BrayCurtis/Gauss handle
        // their parameters.
        bool optionalflag = false;
        for (size_t i = 1; i < command.size(); i++) {
            if (command[i] == "inputfile" || command[i] == "outputfile") {
                continue;
            }
            if (command[i][0] == '[') {
                optionalflag = true;
                continue;
            }
            if (command[i][0] == ']') {
                optionalflag = false;
                continue;
            }
            // Skip the flag itself; only process the parameter name
            // immediately after a flag.
            if (command[i][0] == '-') {
                if (i + 1 < command.size() && command[i + 1] != "inputfile"
                    && command[i + 1] != "outputfile") {
                    if (optionalflag) {
                        r << "  if (\"" << command[i + 1] << "\" %in% rownames(parameters)) {" << std::endl;
                        r << "    " << command[i + 1] << " <<- paste(pfix, parameters[\""
                          << command[i + 1] << "\", 2], sep=\"/\")" << std::endl;
                        r << "  }" << std::endl;
                    } else {
                        r << "  " << command[i + 1] << " <<- paste(pfix, parameters[\""
                          << command[i + 1] << "\", 2], sep=\"/\")" << std::endl;
                    }
                    i++;
                }
                continue;
            }
            // Bare parameter token (no flag).
            if (optionalflag) {
                r << "  if (\"" << command[i] << "\" %in% rownames(parameters)) {" << std::endl;
                r << "    " << command[i] << " <<- paste(pfix, parameters[\""
                  << command[i] << "\", 2], sep=\"/\")" << std::endl;
                r << "  }" << std::endl;
            } else {
                r << "  " << command[i] << " <<- paste(pfix, parameters[\""
                  << command[i] << "\", 2], sep=\"/\")" << std::endl;
            }
        }
    }
    r << "}" << std::endl;
    r << std::endl;

    // run() — empty by convention; existing plugins do work in output().
    r << "run <- function() {}" << std::endl;
    r << std::endl;

    // output() — TODO body for the user. Hint how to access state.
    r << "output <- function(outputfile) {" << std::endl;
    if (myLiteral) {
        r << "  # TODO: read inputfile, compute, and write to outputfile." << std::endl;
        r << "  # data <- read.csv(inputfile)" << std::endl;
        r << "  # ..." << std::endl;
        r << "  # write.csv(result, outputfile)" << std::endl;
    } else {
        r << "  # TODO: use the path globals set in input() and write to outputfile." << std::endl;
        r << "  # ..." << std::endl;
        r << "  # write.csv(result, outputfile)" << std::endl;
    }
    r << "}" << std::endl;

    r.close();
    std::cout << "Generated: " << rfile << std::endl;
}

void RPluginGenerator::makeReadme(std::string pluginname, std::vector<std::string>& command) {
    std::string readme = myPath + "/" + pluginname + "/README.md";
    std::ofstream readmefile(readme.c_str(), std::ios::out);

    std::cout << "ENTER OUTPUT FORMAT: ";
    std::string outputfmt;
    std::cin >> outputfmt;

    std::cout << "ENTER DEPENDENCIES: ";
    std::string dependencies;
    std::cin >> dependencies;

    readmefile << "# " << pluginname << std::endl;
    readmefile << std::endl;
    readmefile << "## Overview" << std::endl;
    readmefile << std::endl;
    readmefile << "- **Language:** R" << std::endl;
    readmefile << "- **Input:** TXT (tab-delimited parameter file)" << std::endl;
    readmefile << "- **Output:** " << outputfmt << std::endl;
    readmefile << "- **Tested with:** PluMA 2.0+, R 4.0+" << std::endl;
    if (!dependencies.empty() && dependencies != "none") {
        readmefile << "- **R packages:** " << dependencies << std::endl;
    }
    readmefile << std::endl;

    readmefile << "## Description" << std::endl;
    readmefile << std::endl;
    readmefile << "PluMA plugin that runs " << pluginname << "." << std::endl;
    readmefile << std::endl;

    readmefile << "## Parameters" << std::endl;
    readmefile << std::endl;
    readmefile << "The plugin expects a parameter file with tab-delimited key/value pairs" << std::endl;
    readmefile << "(one pair per line). Path values are resolved against `prefix()`:" << std::endl;
    readmefile << std::endl;

    bool optionalflag = false;
    for (size_t i = 1; i < command.size(); i++) {
        if (command[i][0] == '[') {
            optionalflag = true;
        } else if (command[i][0] == ']') {
            optionalflag = false;
        } else if (command[i][0] == '-') {
            if (i + 1 < command.size() && command[i + 1] != "inputfile" && command[i + 1] != "outputfile") {
                if (optionalflag) {
                    readmefile << "- `" << command[i + 1] << "` (optional, flag: " << command[i] << ")" << std::endl;
                } else {
                    readmefile << "- `" << command[i + 1] << "` (required, flag: " << command[i] << ")" << std::endl;
                }
                i++;
            }
        } else if (command[i] != "inputfile" && command[i] != "outputfile") {
            if (optionalflag) {
                readmefile << "- `" << command[i] << "` (optional)" << std::endl;
            } else {
                readmefile << "- `" << command[i] << "` (required)" << std::endl;
            }
        }
    }

    readmefile << std::endl;
    readmefile << "## Usage" << std::endl;
    readmefile << std::endl;
    readmefile << "In your PluMA pipeline file:" << std::endl;
    readmefile << std::endl;
    readmefile << "```" << std::endl;
    readmefile << "Plugin " << pluginname << " inputfile params.txt outputfile output." << outputfmt << std::endl;
    readmefile << "```" << std::endl;
    readmefile << std::endl;

    readmefile << "## R Plugin Structure" << std::endl;
    readmefile << std::endl;
    readmefile << "PluMA R plugins are bare top-level functions (no class):" << std::endl;
    readmefile << std::endl;
    readmefile << "```r" << std::endl;
    readmefile << "dyn.load(paste(\"RPluMA\", .Platform$dynlib.ext, sep=\"\"))" << std::endl;
    readmefile << "source(\"RPluMA.R\")" << std::endl;
    readmefile << std::endl;
    readmefile << "input <- function(inputfile) {" << std::endl;
    readmefile << "  # Read parameters; resolve paths with prefix()" << std::endl;
    readmefile << "}" << std::endl;
    readmefile << std::endl;
    readmefile << "run <- function() {}" << std::endl;
    readmefile << std::endl;
    readmefile << "output <- function(outputfile) {" << std::endl;
    readmefile << "  # Main computation; write results to outputfile" << std::endl;
    readmefile << "}" << std::endl;
    readmefile << "```" << std::endl;
    readmefile << std::endl;
    readmefile << "State persists between calls via the `<<-` super-assignment operator." << std::endl;

    readmefile.close();
    std::cout << "Generated: " << readme << std::endl;
}
