/********************************************************************************\

                   Plugin-based Microbiome Analysis (PluMA)

        Copyright (C) 2016, 2018-2020 Bioinformatics Research Group (BioRG)
                       Florida International University


     Permission is hereby granted, free of charge, to any person obtaining
          a copy of this software and associated documentation files
        (the "Software"), to deal in the Software without restriction,
      including without limitation the rights to use, copy, modify, merge,
      publish, distribute, sublicense, and/or sell copies of the Software,
       and to permit persons to whom the Software is furnished to do so,
                    subject to the following conditions:

    The above copyright notice and this permission notice shall be included
            in all copies or substantial portions of the Software.

        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
     IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
     CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
      TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
           SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

       For information regarding this software, please contact lead architect
                    Trevor Cickovski at tcickovs@fiu.edu

\*********************************************************************************/

#include "RustPluginGenerator.h"
#include <dirent.h>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <algorithm>

// Constructor, sets the plugin path
RustPluginGenerator::RustPluginGenerator(std::string path, bool literal) {
    myPath = path;
    myLiteral = literal;
}

// Generate the Rust plugin in the correct folder
void RustPluginGenerator::generate(std::string pluginname, std::vector<std::string>& command) {
    makeDirectory(pluginname);
    makeCargoToml(pluginname);
    makeSourceFile(pluginname, command);
    makeReadme(pluginname, command);
}

void RustPluginGenerator::makeDirectory(std::string pluginname) {
    std::string directory = myPath + "/" + pluginname;
    // Check if directory exists, if so return, if not make it
    DIR* dir = opendir(directory.c_str());
    if (!dir) {
        system(("mkdir -p " + directory + "/src").c_str());
    } else {
        // Create src subdirectory if it doesn't exist
        std::string srcDir = directory + "/src";
        DIR* srcDirPtr = opendir(srcDir.c_str());
        if (!srcDirPtr) {
            system(("mkdir " + srcDir).c_str());
        }
    }
}

void RustPluginGenerator::makeCargoToml(std::string pluginname) {
    std::string cargofile = myPath + "/" + pluginname + "/Cargo.toml";
    std::ofstream cargo(cargofile.c_str(), std::ios::out);

    // Convert plugin name to lowercase with hyphens for crate name
    std::string cratename = pluginname;
    std::transform(cratename.begin(), cratename.end(), cratename.begin(), ::tolower);

    cargo << "[package]" << std::endl;
    cargo << "name = \"" << cratename << "-plugin\"" << std::endl;
    cargo << "version = \"0.1.0\"" << std::endl;
    cargo << "edition = \"2024\"" << std::endl;
    cargo << "description = \"PluMA plugin: " << pluginname << "\"" << std::endl;
    cargo << "license = \"MIT\"" << std::endl;
    cargo << std::endl;
    cargo << "[lib]" << std::endl;
    cargo << "name = \"" << pluginname << "Plugin\"" << std::endl;
    cargo << "crate-type = [\"cdylib\"]" << std::endl;
    cargo << std::endl;
    cargo << "[dependencies]" << std::endl;
    cargo << "pluma-plugin-trait = \"1.1\"" << std::endl;
    cargo << std::endl;
    cargo << "[profile.release]" << std::endl;
    cargo << "opt-level = 3" << std::endl;
    cargo << "lto = true" << std::endl;
}

void RustPluginGenerator::makeSourceFile(std::string pluginname, std::vector<std::string>& command) {
    std::string sourcefile = myPath + "/" + pluginname + "/src/lib.rs";
    std::ofstream rsfile(sourcefile.c_str(), std::ios::out);

    // File header
    rsfile << "//! " << pluginname << " PluMA Plugin" << std::endl;
    rsfile << "//!" << std::endl;
    rsfile << "//! Auto-generated by PluGen" << std::endl;
    rsfile << std::endl;
    rsfile << "use pluma_plugin_trait::PluMAPlugin;" << std::endl;
    rsfile << "use std::ffi::CStr;" << std::endl;
    rsfile << "use std::os::raw::c_char;" << std::endl;
    rsfile << "use std::process::Command;" << std::endl;
    rsfile << "use std::fs;" << std::endl;
    rsfile << "use std::collections::HashMap;" << std::endl;
    rsfile << std::endl;

    // Plugin struct
    rsfile << "/// " << pluginname << " Plugin" << std::endl;
    rsfile << "pub struct " << pluginname << "Plugin {" << std::endl;
    rsfile << "    inputfile: String," << std::endl;
    rsfile << "    outputfile: String," << std::endl;
    rsfile << "    parameters: HashMap<String, String>," << std::endl;
    rsfile << "}" << std::endl;
    rsfile << std::endl;

    // Default implementation
    rsfile << "impl Default for " << pluginname << "Plugin {" << std::endl;
    rsfile << "    fn default() -> Self {" << std::endl;
    rsfile << "        " << pluginname << "Plugin {" << std::endl;
    rsfile << "            inputfile: String::new()," << std::endl;
    rsfile << "            outputfile: String::new()," << std::endl;
    rsfile << "            parameters: HashMap::new()," << std::endl;
    rsfile << "        }" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "}" << std::endl;
    rsfile << std::endl;

    // Helper methods
    rsfile << "impl " << pluginname << "Plugin {" << std::endl;
    rsfile << "    /// Read parameters from a tab-delimited file" << std::endl;
    rsfile << "    fn read_parameter_file(&mut self, filepath: &str) {" << std::endl;
    rsfile << "        if let Ok(contents) = fs::read_to_string(filepath) {" << std::endl;
    rsfile << "            for line in contents.lines() {" << std::endl;
    rsfile << "                let parts: Vec<&str> = line.split('\\t').collect();" << std::endl;
    rsfile << "                if parts.len() >= 2 {" << std::endl;
    rsfile << "                    self.parameters.insert(" << std::endl;
    rsfile << "                        parts[0].trim().to_string()," << std::endl;
    rsfile << "                        parts[1].trim().to_string()" << std::endl;
    rsfile << "                    );" << std::endl;
    rsfile << "                }" << std::endl;
    rsfile << "            }" << std::endl;
    rsfile << "        }" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << std::endl;
    rsfile << "    /// Get a parameter value, with optional prefix path" << std::endl;
    rsfile << "    fn get_param(&self, key: &str) -> Option<String> {" << std::endl;
    rsfile << "        self.parameters.get(key).cloned()" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "}" << std::endl;
    rsfile << std::endl;

    // PluMAPlugin trait implementation
    rsfile << "impl PluMAPlugin for " << pluginname << "Plugin {" << std::endl;

    // input() method
    rsfile << "    fn input(&mut self, file_path: String) -> Result<(), Box<dyn std::error::Error>> {" << std::endl;
    rsfile << "        self.inputfile = file_path.clone();" << std::endl;
    if (!myLiteral) {
        rsfile << "        self.read_parameter_file(&file_path);" << std::endl;
    }
    rsfile << "        Ok(())" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << std::endl;

    // run() method
    rsfile << "    fn run(&mut self) -> Result<(), Box<dyn std::error::Error>> {" << std::endl;
    rsfile << "        // TODO: Implement plugin logic here" << std::endl;
    rsfile << "        Ok(())" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << std::endl;

    // output() method - build and execute command
    rsfile << "    fn output(&mut self, file_path: String) -> Result<(), Box<dyn std::error::Error>> {" << std::endl;
    rsfile << "        self.outputfile = file_path;" << std::endl;
    rsfile << std::endl;

    // Build the command
    if (command.size() > 0) {
        rsfile << "        let mut cmd = Command::new(\"" << command[0] << "\");" << std::endl;
        rsfile << std::endl;

        bool optionalflag = false;
        for (size_t i = 1; i < command.size(); i++) {
            if (myLiteral && command[i] == "inputfile") {
                rsfile << "        cmd.arg(&self.inputfile);" << std::endl;
            } else if (command[i] == "outputfile") {
                rsfile << "        cmd.arg(&self.outputfile);" << std::endl;
            } else if (command[i][0] == '[') {
                optionalflag = true;
            } else if (command[i][0] == ']') {
                optionalflag = false;
            } else if (command[i][0] == '-') {
                if (i + 1 < command.size() && command[i + 1] != "inputfile" && command[i + 1] != "outputfile") {
                    if (optionalflag) {
                        rsfile << "        if let Some(val) = self.get_param(\"" << command[i + 1] << "\") {" << std::endl;
                        rsfile << "            cmd.arg(\"" << command[i] << "\").arg(&val);" << std::endl;
                        rsfile << "        }" << std::endl;
                    } else {
                        rsfile << "        if let Some(val) = self.get_param(\"" << command[i + 1] << "\") {" << std::endl;
                        rsfile << "            cmd.arg(\"" << command[i] << "\").arg(&val);" << std::endl;
                        rsfile << "        } else {" << std::endl;
                        rsfile << "            eprintln!(\"[" << pluginname << "] Warning: Required parameter '" << command[i + 1] << "' not found\");" << std::endl;
                        rsfile << "        }" << std::endl;
                    }
                    i++; // Skip the parameter name
                } else {
                    rsfile << "        cmd.arg(\"" << command[i] << "\");" << std::endl;
                }
            } else if (command[i] != "[" && command[i] != "]") {
                if (optionalflag) {
                    rsfile << "        if let Some(val) = self.get_param(\"" << command[i] << "\") {" << std::endl;
                    rsfile << "            cmd.arg(&val);" << std::endl;
                    rsfile << "        }" << std::endl;
                } else {
                    rsfile << "        if let Some(val) = self.get_param(\"" << command[i] << "\") {" << std::endl;
                    rsfile << "            cmd.arg(&val);" << std::endl;
                    rsfile << "        }" << std::endl;
                }
            }
        }

        rsfile << std::endl;
        rsfile << "        eprintln!(\"[" << pluginname << "] Executing command: {:?}\", cmd);" << std::endl;
        rsfile << std::endl;
        rsfile << "        let status = cmd.status()?;" << std::endl;
        rsfile << "        if !status.success() {" << std::endl;
        rsfile << "            eprintln!(\"[" << pluginname << "] Command failed with status: {}\", status);" << std::endl;
        rsfile << "        }" << std::endl;
    } else {
        rsfile << "        // TODO: Add command execution logic here" << std::endl;
    }

    rsfile << std::endl;
    rsfile << "        Ok(())" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "}" << std::endl;
    rsfile << std::endl;

    // FFI exports
    rsfile << "// =============================================================================" << std::endl;
    rsfile << "// FFI Exports for PluMA" << std::endl;
    rsfile << "// These functions use #[unsafe(no_mangle)] for Rust 2024 edition compatibility" << std::endl;
    rsfile << "// =============================================================================" << std::endl;
    rsfile << std::endl;

    rsfile << "/// Create a new plugin instance" << std::endl;
    rsfile << "#[unsafe(no_mangle)]" << std::endl;
    rsfile << "pub extern \"C\" fn plugin_create() -> *mut std::ffi::c_void {" << std::endl;
    rsfile << "    let plugin = Box::new(" << pluginname << "Plugin::default());" << std::endl;
    rsfile << "    Box::into_raw(plugin) as *mut std::ffi::c_void" << std::endl;
    rsfile << "}" << std::endl;
    rsfile << std::endl;

    rsfile << "/// Destroy a plugin instance" << std::endl;
    rsfile << "#[unsafe(no_mangle)]" << std::endl;
    rsfile << "pub extern \"C\" fn plugin_destroy(ptr: *mut std::ffi::c_void) {" << std::endl;
    rsfile << "    if !ptr.is_null() {" << std::endl;
    rsfile << "        unsafe {" << std::endl;
    rsfile << "            let _ = Box::from_raw(ptr as *mut " << pluginname << "Plugin);" << std::endl;
    rsfile << "        }" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "}" << std::endl;
    rsfile << std::endl;

    rsfile << "/// Execute the input phase" << std::endl;
    rsfile << "#[unsafe(no_mangle)]" << std::endl;
    rsfile << "pub extern \"C\" fn plugin_input(ptr: *mut std::ffi::c_void, filename: *const c_char) {" << std::endl;
    rsfile << "    if ptr.is_null() || filename.is_null() {" << std::endl;
    rsfile << "        return;" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "    unsafe {" << std::endl;
    rsfile << "        let plugin = &mut *(ptr as *mut " << pluginname << "Plugin);" << std::endl;
    rsfile << "        let filename_str = CStr::from_ptr(filename).to_str().unwrap_or(\"\").to_string();" << std::endl;
    rsfile << "        if let Err(e) = plugin.input(filename_str) {" << std::endl;
    rsfile << "            eprintln!(\"[" << pluginname << "] Error in input: {}\", e);" << std::endl;
    rsfile << "        }" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "}" << std::endl;
    rsfile << std::endl;

    rsfile << "/// Execute the run phase" << std::endl;
    rsfile << "#[unsafe(no_mangle)]" << std::endl;
    rsfile << "pub extern \"C\" fn plugin_run(ptr: *mut std::ffi::c_void) {" << std::endl;
    rsfile << "    if ptr.is_null() {" << std::endl;
    rsfile << "        return;" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "    unsafe {" << std::endl;
    rsfile << "        let plugin = &mut *(ptr as *mut " << pluginname << "Plugin);" << std::endl;
    rsfile << "        if let Err(e) = plugin.run() {" << std::endl;
    rsfile << "            eprintln!(\"[" << pluginname << "] Error in run: {}\", e);" << std::endl;
    rsfile << "        }" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "}" << std::endl;
    rsfile << std::endl;

    rsfile << "/// Execute the output phase" << std::endl;
    rsfile << "#[unsafe(no_mangle)]" << std::endl;
    rsfile << "pub extern \"C\" fn plugin_output(ptr: *mut std::ffi::c_void, filename: *const c_char) {" << std::endl;
    rsfile << "    if ptr.is_null() || filename.is_null() {" << std::endl;
    rsfile << "        return;" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "    unsafe {" << std::endl;
    rsfile << "        let plugin = &mut *(ptr as *mut " << pluginname << "Plugin);" << std::endl;
    rsfile << "        let filename_str = CStr::from_ptr(filename).to_str().unwrap_or(\"\").to_string();" << std::endl;
    rsfile << "        if let Err(e) = plugin.output(filename_str) {" << std::endl;
    rsfile << "            eprintln!(\"[" << pluginname << "] Error in output: {}\", e);" << std::endl;
    rsfile << "        }" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "}" << std::endl;
    rsfile << std::endl;

    // Tests
    rsfile << "#[cfg(test)]" << std::endl;
    rsfile << "mod tests {" << std::endl;
    rsfile << "    use super::*;" << std::endl;
    rsfile << std::endl;
    rsfile << "    #[test]" << std::endl;
    rsfile << "    fn test_plugin_creation() {" << std::endl;
    rsfile << "        let plugin = " << pluginname << "Plugin::default();" << std::endl;
    rsfile << "        assert!(plugin.inputfile.is_empty());" << std::endl;
    rsfile << "        assert!(plugin.outputfile.is_empty());" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << std::endl;
    rsfile << "    #[test]" << std::endl;
    rsfile << "    fn test_ffi_lifecycle() {" << std::endl;
    rsfile << "        let ptr = plugin_create();" << std::endl;
    rsfile << "        assert!(!ptr.is_null());" << std::endl;
    rsfile << "        plugin_destroy(ptr);" << std::endl;
    rsfile << "    }" << std::endl;
    rsfile << "}" << std::endl;
}

void RustPluginGenerator::makeReadme(std::string pluginname, std::vector<std::string>& command) {
    std::string readme = myPath + "/" + pluginname + "/README.md";
    std::ofstream readmefile(readme.c_str(), std::ios::out);

    std::cout << "ENTER OUTPUT FORMAT: ";
    std::string outputfmt;
    std::cin >> outputfmt;

    std::cout << "ENTER DEPENDENCIES (comma-separated crate names, or 'none'): ";
    std::string dependencies;
    std::cin >> dependencies;

    readmefile << "# " << pluginname << std::endl;
    readmefile << std::endl;
    readmefile << "- **Language**: Rust" << std::endl;
    readmefile << "- **Input**: TXT (parameter file)" << std::endl;
    readmefile << "- **Output**: " << outputfmt << std::endl;
    readmefile << "- **Tested with**: PluMA 2.1, Rust 1.70+" << std::endl;
    if (dependencies != "none" && !dependencies.empty()) {
        readmefile << "- **Dependencies**: " << dependencies << std::endl;
    }
    readmefile << std::endl;

    readmefile << "## Description" << std::endl;
    readmefile << std::endl;
    readmefile << "PluMA plugin that runs " << pluginname << "." << std::endl;
    readmefile << std::endl;

    readmefile << "## Building" << std::endl;
    readmefile << std::endl;
    readmefile << "```bash" << std::endl;
    readmefile << "cd " << pluginname << std::endl;
    readmefile << "cargo build --release" << std::endl;
    readmefile << "```" << std::endl;
    readmefile << std::endl;

    readmefile << "## Installation" << std::endl;
    readmefile << std::endl;
    readmefile << "Copy the built shared library to your PluMA plugins directory:" << std::endl;
    readmefile << std::endl;
    readmefile << "```bash" << std::endl;
    readmefile << "cp target/release/lib" << pluginname << "Plugin.so $PLUMA_PLUGIN_PATH/" << pluginname << "/" << std::endl;
    readmefile << "```" << std::endl;
    readmefile << std::endl;

    readmefile << "## Parameters" << std::endl;
    readmefile << std::endl;
    readmefile << "The plugin expects a tab-delimited parameter file with the following keys:" << std::endl;
    readmefile << std::endl;

    bool optionalflag = false;
    for (size_t i = 1; i < command.size(); i++) {
        if (command[i][0] == '[') {
            optionalflag = true;
        } else if (command[i][0] == ']') {
            optionalflag = false;
        } else if (command[i][0] == '-') {
            if (i + 1 < command.size() && command[i + 1] != "inputfile" && command[i + 1] != "outputfile") {
                if (optionalflag) {
                    readmefile << "- `" << command[i + 1] << "` (optional, flag: `" << command[i] << "`)" << std::endl;
                } else {
                    readmefile << "- `" << command[i + 1] << "` (required, flag: `" << command[i] << "`)" << std::endl;
                }
                i++;
            }
        } else if (command[i] != "inputfile" && command[i] != "outputfile" && command[i] != "[" && command[i] != "]") {
            if (optionalflag) {
                readmefile << "- `" << command[i] << "` (optional)" << std::endl;
            } else {
                readmefile << "- `" << command[i] << "` (required)" << std::endl;
            }
        }
    }

    readmefile << std::endl;
    readmefile << "## Output" << std::endl;
    readmefile << std::endl;
    readmefile << "Plugin output format: " << outputfmt << std::endl;
    readmefile << std::endl;

    readmefile << "## License" << std::endl;
    readmefile << std::endl;
    readmefile << "MIT License" << std::endl;
}
