name: PluMA Testing
on:
    push:
        branches: [master, develop]

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v2

            - name: Build container
              run: docker build -t pluma:latest .

            - name: Download plugins
              run: python3 ./Plugins.py download

            - name: Run tests
              run: docker -v "$PWD/plugins":/app/plugins -v "$PWD/pipelines":/app/pipelines -v "$PWD/logs":/app/logs -t pluma:latest python3 ./testPluma.py
