name: PluMA Testing
on:
  push:
    branches: [master, develop]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the docker image
        run: docker build -t fiubiorg/pluma .
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: fiubiorg/pluma
          args: --file=Dockerfile

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt-get install -y scons swig r-base perl python3-pip
      - name: install R packages
        run: sudo Rscript -e 'install.packages("r-inside")'
      - name: install plugins
        run: ./plumadmn download
      - name: build applicaiton
        run: scons
      - name: run tests
        run: python3 ./testPluMA.py
